services:
  nats-hub:
    image: nats:latest
    command: ["-c", "/etc/nats/nats-hub.conf"]
    volumes:
      - ./nats-config/nats-hub.conf:/etc/nats/nats-hub.conf
    ports:
      - "3222:4222"

  nats-a:
    image: nats:latest
    command: ["-c", "/etc/nats/nats-a.conf"]
    ports:
      - "4222:4222"
    volumes:
      - ./nats-config/nats-a.conf:/etc/nats/nats-a.conf
    depends_on:
      - nats-hub

  nats-b:
    image: nats:latest
    command: ["-c", "/etc/nats/nats-b.conf"]
    ports:
      - "5222:4222"
    volumes:
      - ./nats-config/nats-b.conf:/etc/nats/nats-b.conf
    depends_on:
      - nats-hub
